### ISSUE TITLE
Is this plugin still updated? Supported?

### ISSUE THREAD

**Issue by TomLewis** [AlonsoAliaga/AlonsoTags#14]
Im trying to make a decision if I should use DeluxeTags or AlonsoTags as they seem like the only two options on Spigot, but im worried about the last update being in 2021. 2 years ago.
Does this get updated outside of Spigot?

**Comment by AlonsoAliaga** [comment]
DeluxeMenus is a menu plugin, AlonsoTags is a tags plugin, if you meant DeluxeTags (if you dont need msyql, its all find, you can try it). As you can see AlonsoTags supports 1.19, how if it was updated 2 years ago? Well, code was made so even if something happens to me, plugin should still work fine for years (just updating required dependencies). No it's not updated outside spigotmc, plan to release an update soon, but im not giving any ETA so you dont buy it because i said that. You can try free version so you make sure it does work in your server version, for more questions you can join us on https://alonsoaliaga.com/discord
