### ISSUE TITLE
Player's data about which tags unlock is uneditable by admin or command

### ISSUE THREAD

**Issue by CactusMikaz** [AlonsoAliaga/AlonsoTags#4]
NOTICE THAT THIS IS JUST A REQUEST. FEATURE CAN NEVER BE ADDED.

**Is your feature request related to a problem? Please describe.**
I found out some tags could add price that player could buy it and use it, so I'm doing some test on this, then I found out there is no way to remove a tag that unlock by money.

**Describe the solution you'd like**
So may be add a command that could remove player's unlock tags?

**Describe alternatives you've considered**

**Additional context**

**Comment by AlonsoAliaga** [comment]
Yes, there is no way to remove purchased tags (thats why it's not mentioned in features list). Working with offline players data is not east and usually leads to synchronization issues.
That's why it not added. Maybe (just maybe) in a future, a command to remove purchased tags only from online players might be added. But that's a possibility only

**Comment by CactusMikaz** [comment]
I was thinking if I could not check, give, remove players data of this plugin, maybe I will use permission to manage player's unlock tags.
If I need to make player buy tags with in-game currency, I will use another shop plugin like BossShopPro to make create a shop that sell permission that unlock specific tags.

**Comment by AlonsoAliaga** [comment]
Understandable, but as mentioned remember that modifying offline tags (as mentioned) might create issurs internally (and thats why i havent added it)

**Comment by CactusMikaz** [comment]
Okay, I fully understand what your concerned about it, should I close this issue?
